### ISSUE TITLE
Recap

### ISSUE THREAD

**Issue by Gius30** [Manillin/ProgettoSoftware#1]
Buongiorno guys ho fatto i punti 2.4 , 2.5 , 2.6 mi sono fattto aiutare da chat gpt , il punto 2.6 non l'ho fatto perchè non ho capito cosa vuole . In realtà è tutto molto confuso perchè a mio parere abbiamo pochissimi esempi ed informazioni su cosa dobbiamo scrivere.

Cordiali saluti.

_Giuseppe Nutricato_

**Comment by lucaAnza** [comment]
Perfect
